schemaVersion: 2.3.0
metadata:
  name: wazi-udi

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: wazi-terminal
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.16
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
