schemaVersion: 2.3.0
metadata:
  name: idz-devspaces

components:
  - name: zowe
    volume:
      size: 100Mi
  - name: idz-terminal
    container:
      image: icr.io/wazi-code/ibm-wazi-for-devspaces-sidecar:latest
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/user/.zowe
