schemaVersion: 2.1.0
metadata:
  name: wazi-demo

components:
  - name: wazi-terminal
    container:
      image: icr.io/wazi-code/ibm-wazi-for-devspaces-codeready@sha256:0bf8460efac9db509eb1d0788077caea31cbaf0e5ac2208385403a35ca4757c2
      memoryLimit: 1024Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/wazi/.zowe
  - name: zowe
    volume:
      size: 1G
