schemaVersion: 2.2.0
metadata:
  name: wazi-udi

components:
  - name: wazi-terminal
    container:
      image: registry.redhat.io/devspaces/udi-rhel8:3.16
      memoryLimit: 3072Mi
      mountSources: true
      volumeMounts:
        - name: zowe
          path: /home/wazi/.zowe
  - name: zowe
    volume:
      size: 100Mi
