 /****************************************************************
  * LICENSED MATERIALS - PROPERTY OF IBM
  * "RESTRICTED MATERIALS OF IBM"
  * (C) COPYRIGHT IBM CORPORATION 2021. ALL RIGHTS RESERVED
  * US GOVERNMENT USERS RESTRICTED RIGHTS - USE, DUPLICATION,
  * OR DISCLOSURE RESTRICTED BY GSA ADP SCHEDULE
  * CONTRACT WITH IBM CORPORATION
  ****************************************************************/
   DCL 1 SYSTEM_DATE_AND_TIME,
         2 CURRENT_DATE,
           3 CURRENT_YEAR            PIC '9999',
           3 CURRENT_MONTH           PIC '99',
           3 CURRENT_DAY             PIC '99',
         2 CURRENT_TIME,
           3 CURRENT_HOUR            PIC '99',
           3 CURRENT_MINUTE          PIC '99',
           3 CURRENT_SECOND          PIC '99',
           3 CURRENT_MILLISEC        PIC '999';
