---
###############################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2021, 2022. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
###############################################################################

################################################################################
# Change these ports if you are using a Wazi Sandbox to the NodePort values
# that you find in the svc-cicd-wazisandboxsystem-adcd-nazare service details
# page in OpenShift. Commnands to retrieve these would look like this
# oc project wazi-sandbox
# oc get wazisandboxsystems
# oc get -o yaml -n wazi-sandbox service svc-cicd-wazisandboxsystem-adcd-nazare
#
# TODO: automatically parse results from
# oc get  -n wazi-sandbox -l 'app.kubernetes.io/instance==cicd-wazisandboxsystem-adcd-nazare' service
################################################################################

ftp_port: 30667                   # default: 21
ssh_port: 31652                   # default: 22
tn3270_unsecure_port: 32226       # default: 23
tn3270_secure_port: 30207         # default: 2023

# Verify Debug SSL certifcate and ports by accessing
# https://ip-address:debug_profile_service_port_ssl/api/v1/remote-debug/config
remote_debug_service_port: 30710
debug_profile_service_port: 30185
debug_profile_service_port_ssl: 8192
local_debug_port: 7393
debug_manager_port: 31649

rse_api_port: 31046               # default: 7395
rsed_port: 30929                  # default: 4035
rse_server_port: 30716            # default: 4037
zosmf_port: 32505                 # default: 10443

################################################################################
# Change these values related for your z/OS configuration
################################################################################

# Cobol Compiler Data Sets. Example: COBOL.V4R1M0.SIGYCOMP
cobol6_compiler_library: IGY630.SIGYCOMP

link_library: CEE.SCEELKED
debug_library: ISM330

# z/OS macro library. Example: SYS1.MACLIB
hlasm_maclib: SYS1.MACLIB
# Assembler macro library. Example: CEE.SCEEMAC
hlasm_sceemac: CEE.SCEEMAC
# High Level Assembler (HLASM) load library. Example: ASM.SASMMOD1
hlasm_sasmod1: HLA.SASMMOD1

# PL/I Compiler Data Sets.  Example: PLI.V5R2M0.SIBMZCMP
ibmzpli_v61: IEL610.SIBMZCMP

# REXX Compiler Data Sets. Example: REXX.V1R4.SFANLMD
sfanlmd: FAN140.SFANLMD

# CICS Macro Library. Example: CICSTS.V3R2M0.CICS.SDFHMAC
sdfhmac: DFH560.CICS.SDFHMAC
# CICS Load Library. Example: CICSTS.V3R2M0.CICS.SDFHLOAD
sdfhload: DFH560.CICS.SDFHLOAD
# CICS COBOL Library. Example: CICSTS.V3R2M0.CICS.SDFHCOB
sdfhcob: DFH560.CICS.SDFHCOB

# MQ COBOL Library. Example: CSQ.V9R1M0.SCSQCOBC
scsqcobc: CSQ920.SCSQCOBC
# MQ Load Library. Example: CSQ.V9R1M0.SCSQLOAD
scsqload: CSQ920.SCSQLOAD

# DB2 Load Library. Example: DB2.V9R1M0.SDSNLOAD
sdsnload: DSNC10.SDSNLOAD

# IMS Macro Library. Example: DFS.V11R1M0.SDFSMAC
sdfsmac: DFSF10.SDFSMAC
# IMS RESLIB. Example: DFS.V11R1M0.SDFSRESL
sdfsresl: DFSF10.SDFSRESL

# User generated library for DB/DC and DC installations. Example: DFS.V11R1M0.REFERAL
referal: DFSF10.REFERAL

# Optional IDz Load Library. Example: FEL.V14R0M0.SFELLOAD
sfelload: ISM330.SFELLOAD

# Optional IDZ zUnit / WAZI VTP library containing necessary copybooks. Example : FEL.V14R2.SBZUSAMP
sbzusamp: ISM330.SBZUSAMP

################################################################################
# Description of the properties used in this configuration:
# - Property `pyz` is the python installation home path on the z/OS managed node (target),
#    e.g, pyz: "/usr/lpp/IBM/cyp/v3r8/pyz"
# - Property `zoau` is the ZOAU installation home on the z/OS managed node (target),
#    e.g, zoau: "/usr/lpp/IBM/zoautil"
# - property `ansible_python_interpreter` is the z/OS managed node (target) Python
#    binary installation path, e.g, ansible_python_interpreter: "{{pyz}}/bin/python3.8"
################################################################################

pyz: "/usr/lpp/IBM/cyp/v3r9/pyz"
ansible_python_interpreter: "{{ pyz }}/bin/python3.9"
zoau: "/usr/lpp/IBM/zoautil"
rocket: "/usr/lpp/Rocket/rsusr/ported"
java_home: "/usr/lpp/java/J8.0_64"
dbb_home: "/usr/lpp/IBM/dbb"
dbb_conf: "/etc/dbb"
dbb_version: 2
dbb_settings: "-DBB_PERSONAL_DAEMON"
