###############################################################################
# Licensed Materials - Property of IBM
# (c) Copyright IBM Corporation 2021, 2024. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
# Use, duplication or disclosure restricted by GSA ADP Schedule
# Contract with IBM Corp.
###############################################################################

## Playbook that creates local Zowe profiles for the host provided

---
- name: Initialize local files in developer workspace
  hosts: "{{ host | default('sandbox1') }}"
  # collections:
  #  - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"

  vars_prompt:
    - name: password
      prompt: "Password for the z/OS user?"
    - name: editor
      prompt: "Are you using Z Open Editor (vscode) or Wazi for Workspaces (che)? Enter 'vscode' or 'che'"
      default: "vscode"
      private: false
    - name: overwrite
      prompt: "Do you want to automatically overwrite your existing configuration files? Enter 'yes' or 'no'"
      default: "no"
      private: false

  tasks:
    # Variables and template prep
    - name: Defining user-specific variables
      ansible.builtin.set_fact:
        hlq: "{{ ansible_user | upper }}"

    - name: Generating Zowe CLI profile config file.
      ansible.builtin.template:
        src: zowe.config.j2
        dest: ~/.zowe/zowe.config.GEN.json
        mode: u+rw
      delegate_to: localhost

    - name: Automatically replacing an existing Zowe CLI profiles config file
      ansible.builtin.command:
        cmd: mv -f ~/.zowe/zowe.config.GEN.json ~/.zowe/zowe.config.json
      when: overwrite == "yes"
      changed_when: overwrite == "yes"
      delegate_to: localhost

    - name: On Che executing Zowe CLI schema merge for automatically replaced Zowe Config file
      ansible.builtin.command:
        cmd: /usr/bin/zowe config update-schemas
      when: overwrite == "yes" and editor == "che"
      changed_when: overwrite == "yes" and editor == "che"
      delegate_to: localhost

    - name: On VS Code tell user to manually finish Zowe CLI profile configuration for automatically replaced Zowe Config file
      ansible.builtin.debug:
        msg:
          - "To finish configure configuration of your  Zowe CLI profiles for '{{ ansible_host }}' run these commmands"
          - "zowe config update-schemas"
      when: overwrite == "yes" and editor == "vscode"
      delegate_to: localhost

    - name: Zowe CLI profile config file created in new file
      ansible.builtin.debug:
        msg:
          - "To finish configure configuration of your  Zowe CLI profiles for '{{ ansible_host }}' run these commmands"
          - "mv -f ~/.zowe/zowe.config.GEN.json ~/.zowe/zowe.config.json"
          - "zowe config update-schemas"
      when: overwrite == "no"
      delegate_to: localhost

    - name: Generate schema file when in overwrite mode
      ansible.builtin.template:
        src: zowe.schema.j2
        dest: ~/.zowe/zowe.schema.json
        mode: ugo+rw
      when: overwrite == "yes"
      changed_when: overwrite == "yes"
      delegate_to: localhost

    - name: Generating Debug launch
      ansible.builtin.template:
        src: debug-launch.j2
        dest: ~/.zowe/launch.json
        mode: ugo+rw
      delegate_to: localhost

    - name: Replacing Debug launch file in local workspace
      ansible.builtin.command:
        chdir: ../.vscode
        cmd: mv -f ~/.zowe/launch.json .
      when: overwrite == "yes"
      changed_when: overwrite == "yes"
      delegate_to: localhost

    - name: Generated Debug launch file needs to be manually copied
      ansible.builtin.debug:
        msg: "Copy or merge the generated launch file '~/.zowe/launch.json' for the host {{ ansible_host }} to your workspace directory .vscode or .theia."
      when: overwrite == "no"
      delegate_to: localhost
