   DCL 1 PRODUCT_STATS,                                                 
         2 RECORD_COUNT      DEC(8),                                    
         2 SERV_CALLS_TOTAL  DEC(12,2),                                 
         2 SERV_CALLS_MIN    DEC(12,2),                                 
         2 SERV_CALLS_MAX    DEC(12,2),                                 
         2 SERV_CALLS_RANGE  DEC(12,2),                                 
         2 SERV_CALLS_AVG    DEC(12,2),                                 
         2 PRODUCT_FIRST_TIME_SW     PIC '9';                           
